# Generated by Django 2.0.7 on 2018-07-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_url1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='url1',
        ),
    ]
