# Generated by Django 2.0.7 on 2018-07-15 04:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_url1'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='facultyname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
